---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: proxy
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
        - key: "proxy-taint"
          operator: "Equal"
          value: "nginx"
          effect: "NoSchedule"
      nodeSelector:
        nodegroup: nginx
      containers:
        - name: nginx
          image: nginx:1.14.2
          resources:
            requests:
              cpu: "2"
              memory: 4Gi
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-deployment
  namespace: proxy
  labels:
    app: traefik
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      tolerations:
        - key: "proxy-taint"
          operator: "Equal"
          value: "traefik"
          effect: "NoSchedule"
      nodeSelector:
        nodegroup: traefik
      containers:
        - name: traefik
          image: traefik:v3.5.0
          resources:
            requests:
              cpu: "2"
              memory: 4Gi
          ports:
            - containerPort: 80
