---
apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: basic
spec:
  # module.eks.node_iam_role_arn
  role: "eks-auto-v1-eks-auto-20250925102449654100000002"
  subnetSelectorTerms:
    - tags:
        Name: "eks-auto-v1-private*"
  securityGroupSelectorTerms:
    - tags:
        Name: "eks-auto-v1-node"
  ephemeralStorage:
    size: "80Gi"    
    iops: 3000      
    throughput: 125 
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: basic-node-pool
spec:
  template:
    metadata:
      labels:
        type: basic-node-pool
    spec:
      taints:
        - key: amd64
          effect: NoSchedule
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "eks.amazonaws.com/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "eks.amazonaws.com/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "eks.amazonaws.com/instance-generation"
          operator: Gt
          values: ["4"]
      nodeClassRef:
        name: basic
        group: eks.amazonaws.com
        kind: NodeClass
  limits:
    cpu: 1000
