---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: basic-ingress-class
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: eks.amazonaws.com/alb
  parameters:
    apiGroup: eks.amazonaws.com
    kind: IngressClassParams
    name: basic-class-params
