pull:
	@aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 678468774710.dkr.ecr.eu-west-2.amazonaws.com
	@docker pull 678468774710.dkr.ecr.eu-west-2.amazonaws.com/playground/foo:944d25d
